### ISSUE TITLE
Gecikmelerin kaynaklarının araştırılması

### ISSUE THREAD

**Issue by Astronot1997** [palmScooterArge/palmIotArge#19]
Sürelerin tespit edilmesi

**Comment by ErayTuncan** [comment]
Bahadır sen osiloskop getirince bunları osiloskop ile bakalım. Pinleri high low yaparız. Osiloskoptan ölçeriz.

**Comment by Astronot1997** [comment]
Mantıklı hareket, daha temiz olur.
