### ISSUE TITLE
Bazı R0 isteklerine cevap veremiyor

### ISSUE THREAD

**Issue by Astronot1997** [palmScooterArge/palmIotArge#5]
Peş peşe gelen R0 isteklerine cevap veremiyor,  L0/L1 için acknowledgement beklerken R0 gelince onu okuyor ve başarısız oluyor. Bir çeşit timeout'a ihtiyacı var.

**Comment by ErayTuncan** [comment]
düzelttiğimi sanıyorum ama denemek lazım

**Comment by Astronot1997** [comment]
İsteklerin hepsine cevap veriyor ama server tarafı key hatalarını çözmüyor sorun serverdaki handlerda.
